/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnedContract } from "./OwnedContract";

export { OwnedContract__factory } from "./factories/OwnedContract__factory";
