/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MigrationInterface extends ethers.utils.Interface {
  functions: {
    "migrate()": FunctionFragment;
    "migrationSingleton()": FunctionFragment;
    "safe120Singleton()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "migrate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "migrationSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safe120Singleton",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrationSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safe120Singleton",
    data: BytesLike
  ): Result;

  events: {
    "ChangedMasterCopy(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangedMasterCopy"): EventFragment;
}

export type ChangedMasterCopyEvent = TypedEvent<
  [string] & { singleton: string }
>;

export class Migration extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MigrationInterface;

  functions: {
    migrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    migrationSingleton(overrides?: CallOverrides): Promise<[string]>;

    safe120Singleton(overrides?: CallOverrides): Promise<[string]>;
  };

  migrate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  migrationSingleton(overrides?: CallOverrides): Promise<string>;

  safe120Singleton(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    migrate(overrides?: CallOverrides): Promise<void>;

    migrationSingleton(overrides?: CallOverrides): Promise<string>;

    safe120Singleton(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ChangedMasterCopy(address)"(
      singleton?: null
    ): TypedEventFilter<[string], { singleton: string }>;

    ChangedMasterCopy(
      singleton?: null
    ): TypedEventFilter<[string], { singleton: string }>;
  };

  estimateGas: {
    migrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    migrationSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    safe120Singleton(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    migrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    migrationSingleton(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safe120Singleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
